development:
  adapter: postgresql
  encoding: unicode
  database: tube_development
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tube_test
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: